#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a serve
_JAIL="$4"
if [[ -z "$_JAIL" ]];
then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
else
	scp -i $4 -o StrictHostKeyChecking=no -r $1 $3@$2:/~/
fi
