#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx
ufw allow 'Nginx Full'
service nginx start
echo "Hello World!\n" | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
