#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes
hours=0
minutes=60
while (( hours < 13 )); do
	if [ $minutes -eq 59 ]; then
		echo "Hour: $hours"
		((minutes=1))
		((hours++))
	else
		echo "$minutes"
		((minutes++))
	fi
done
